More POSIX fixes

diff --git a/build_info/firmware-sbin.postrm b/build_info/firmware-sbin.postrm
--- a/build_info/firmware-sbin.postrm
+++ b/build_info/firmware-sbin.postrm
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-if [ "$1" = abort-install ] || [ "$1" = abort-upgrade ]; then
+if [ "$1" = "abort-install" ] || [ "$1" = "abort-upgrade" ]; then
 	LIST="/sbin/fsck /sbin/fsck_apfs /sbin/fsck_exfat /sbin/fsck_hfs /sbin/fsck_msdos /sbin/launchd /sbin/mount
 	/sbin/mount_apfs /sbin/mount_hfs /sbin/newfs_apfs /sbin/newfs_hfs /sbin/pfctl /usr/sbin/BTAvrcp
 	/usr/sbin/BTLEServer /usr/sbin/BTMap /usr/sbin/BTPbap /usr/sbin/BlueTool
@@ -14,7 +14,7 @@ if [ "$1" = abort-install ] || [ "$1" = abort-upgrade ]; then
 			if [ -s "${bin}" ]; then
 				rm -f -v "${bin}".sbin
 			else
-				mv -f -v "${bin}"{.sbin,} || exit 1
+				mv -f -v "${bin}".sbin "${bin}" || exit 1
 			fi
 		fi
 	done
